services:
  db:
    image: postgres
    command: -c 'max_connections=500'
    restart: always
    environment: 
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
